### ISSUE TITLE
Gitlab 自建仓库服务器 | 雪山飞狐

### ISSUE THREAD

**Issue by gitslagga** [gitslagga/gitslagga.github.io#17]
https://slagga.top/2019/11/03/server/Gitlab%E8%87%AA%E5%BB%BA%E4%BB%93%E5%BA%93%E6%9C%8D%E5%8A%A1%E5%99%A8/#more 

 涉及技术领域有Go, Nodejs, Php, 区块链技术等

**Comment by gitfade** [comment]
第一个沙发我占了，永远有我的足迹。

**Comment by kilvn** [comment]
gitlab 还是太重了，Gitea轻量化，一个可执行程序，然后ngxin反代端口就得了，
参考：https://git.kilvn.com/kilvn

**Comment by gitslagga** [comment]
这个就见仁见智了，适合自己的就是最合适的，对自己来说那个效率高就用哪个。
